pipeline {
    agent any
    environment {
            SSH_PASSWORD = credentials('ncp-password')
        }
    tools {
        gradle 'gradle'
    }
    stages {
        stage('Git Clone') {
            steps {
                git branch: 'main', url: 'https://github.com/Tour-KK/BE-CHONS.git'
            }
        }
        stage('Add Application') {
            steps {
                    withCredentials([file(credentialsId: 'application', variable: 'application')]) {
                       sh '''
                            cp ${application}  src/main/resources/application.yml
                            chmod 777 src/main/resources/application.yml
                       '''
                }
            }
        }
        stage('Add Application Prod') {
                    steps {
                            withCredentials([file(credentialsId: 'application-prod', variable: 'application_prod')]) {
                               sh '''
                                    cp ${application_prod}  src/main/resources/application-prod.yml
                                    chmod 777 src/main/resources/application-prod.yml
                               '''
                        }
                    }
                }
        stage('Build') {
            steps {
                sh "./gradlew clean build"
            }
        }
        stage('Deploy') {
                    steps {
                        sshagent(credentials: ['chons-ncp']) {
                            sh '''
                                sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no root@223.130.131.166 uptime
                                sshpass -p $SSH_PASSWORD scp /var/jenkins_home/workspace/chons/build/libs/BE-CHONS-0.0.1-SNAPSHOT.jar root@223.130.131.166:/home/root/chons
                                sshpass -p $SSH_PASSWORD ssh root@223.130.131.166 ./deploy.sh 'nohup ./deploy.sh > /dev/null 2>&1 &'
                            '''
                        }
                    }
        }
    }
}